version: '3.6'

services:

  # Backend API
  smart-api:
    container_name: backend
    #image: node:11
    build: ./
    command: bash -c "npm install && npm start"
    working_dir: /usr/src/smartApi
    environment:
      POSTGRES_URI: postgres://alex:superPassword@postgres:5432/smartDocker
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smartApi

  # Postgres
  postgres:
    container_name: DB
    build: ./postgres
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: superPassword
      POSTGRES_DB: smartDocker
      POSTGRES_HOST: postgres
    ports:
      - "5555:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6399:6379"